spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: eventhub
    password: eventhub
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081